### ISSUE TITLE
Failed to find server with chunks? 

### ISSUE THREAD

**Issue by Blunderfluff** [SteamRE/DepotDownloader#270] opened 2021-10-31 10:12 UTC
Got CDN auth token for steampipe.akamaized.net result: OK (expires 7/11/2021 10:59:06 AM)
Got CDN auth token for steampipe.steamcontent.com result: Fail (expires 1/01/1970 12:00:00 AM)
Disconnected from Steam
Failed to find any server with chunk 3f002061b6faa345fe4a69801464d9e29ed0254f for depot 274521. Aborting.
Failed to find any server with chunk 41d5986c8bb4084baaa4c1d1b691a9a075cdbdf1 for depot 274521. Aborting.
App 274520 was not completely downloaded.
The operation was canceled.

Trying to download old version of Darkwood, but keep running into this problem. Here is my command configuration. Trying to get Alpha 4.2. Any help is appreciated. 

dotnet DepotDownloader.dll -app 274520 -depot 274521 -manifest 2962052644160411129 -username * -password *

**Comment by Blunderfluff** [comment] 2021-11-03 13:34
It seems this was some type of bug or incompatibility in 2.43. Funny thing is, I didn't even know there was a newer version until reading posts. Web search took me to straight to 243 lol. Open my eyes next time.

**Comment by azuisleet** [comment] 2021-11-12 02:10
Without a debug log, it's impossible to tell what the issue is. It's likely this is resolved in 2.4.5.

**Closed by azuisleet** 2021-11-12 02:10 UTC
