### ISSUE TITLE
depot downloader will stop working after logging in

### ISSUE THREAD

**Issue by depothaserror13232** [SteamRE/DepotDownloader#227] opened 2021-07-01 21:33 UTC
https://imgur.com/3n2o02K
as seen in the image linked above
once it logs in it does nothing
it takes forever and just gets new session token
what am i doing wrong?

![](https://i.imgur.com/3n2o02K.png)

**Comment by psychonic** [comment] 2021-07-01 22:22
Duplicate of #226

**Closed by psychonic** 2021-07-01 22:22 UTC
