### ISSUE TITLE
STEAMCDNTOKEN cannot be retrieved without a return, but steam.exe is functioning without any issues. Please fix this issue.

### ISSUE THREAD

**Issue by huddhudd** [SteamRE/DepotDownloader#547] opened 2024-10-11 17:27 UTC
### What did you expect to happen?

STEAMCDNTOKEN cannot be retrieved without a return, but steam.exe is functioning without any issues. Please fix this issue.

### Instead of that, what actually happened?

STEAMCDNTOKEN cannot be retrieved without a return, but steam.exe is functioning without any issues. Please fix this issue.

### Which operating system are you running on?

Windows

### Version

5.2

### Command

 .\DepotDownloader.exe -app 578080

### Relevant log output

Using Steam3 suggested CellID: 204
Got 101 licenses for account!
Got AppInfo for 578080
Using app branch: 'public'.
Got AppInfo for 228980
Got depot key for 228985 result: OK
Got depot key for 228986 result: OK
Got depot key for 228987 result: OK
Got depot key for 228990 result: OK
Got depot key for 578081 result: OK
Got depot key for 578082 result: OK
Processing depot 228985
Downloading depot manifest... Got manifest request code for 228985 3966345552745568756 result: 13962538911309361709
App 578080 was not completely downloaded.
A task was canceled.
Disconnected from Stea

**Comment by xPaw** [comment] 2024-10-13 08:24
Duplicate of #545

**Closed by xPaw** 2024-10-13 08:24 UTC
Labels: bug
