### ISSUE TITLE
[BUG]: DepotDownload does not find public branch even though it exists

### ISSUE THREAD

**Issue by Hope-IT-Works** [SteamRE/DepotDownloader#436] opened 2023-06-12 15:43 UTC
### What did you expect to happen?

When i run `DepotDownloader.exe -app 1690800 -dir "C:\Users\Tobias\Downloads\SatisfactoryServer"`, i expect to download the given app (by id) to the given directory.

### Instead of that, what actually happened?

DepotDownload does not find public branch even though it exists: https://steamdb.info/app/1690800/depots/?branch=public

### Which operating system are you running on?

Windows

### Version

2.4.7

### Relevant log output

```shell
No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 89
Got AppInfo for 1690800
Using app branch: 'Public'.
Warning: Depot 1004 does not have branch named "Public". Trying public branch.
Depot 1004 () missing public subsection or manifest section.
Warning: Depot 1690801 does not have branch named "Public". Trying public branch.
Depot 1690801 () missing public subsection or manifest section.
Total downloaded: 0 bytes (0 bytes uncompressed) from 0 depots
Disconnected from Steam
```

**Comment by yaakov-h** [comment] 2023-06-13 02:23
This look like a duplicate of #428.

**Closed by yaakov-h** 2023-06-13 02:23 UTC
Labels: bug
