### ISSUE TITLE
Connection To Steam Failed... Trying Again

### ISSUE THREAD

**Issue by QuantumRobloxReal** [SteamRE/DepotDownloader#553] opened 2024-10-20 20:27 UTC
### What did you expect to happen?

I thought it was a password typo but it wasnt and everything i tried everything and it done the same

### Instead of that, what actually happened?

Ive been trying for weeks and its not been connecting at all

### Which operating system are you running on?

Windows

### Version

Latest 2.7.3

### Command

dotnet "C:\Users\*****\Desktop\depotdownloader\DepotDownloader.dll" -app 344670 -depot 344671 -manifest 5950600556578212996 -dir C:\Users\Jayde\Documents\de\344670 -max-servers 50 -max-downloads 16

### Additional Information

Please help as soom as possible please!

**Comment by QuantumRobloxReal** [comment] 2024-10-20 20:29
Sorry for any typos

**Comment by xPaw** [comment] 2024-10-21 11:50
Duplicate of #546

**Closed by xPaw** 2024-10-21 11:50 UTC
Labels: bug
