### ISSUE TITLE
Cannot connect to Steam3

### ISSUE THREAD

**Issue by SturdyStubs** [SteamRE/DepotDownloader#550] opened 2024-10-15 05:57 UTC
### What did you expect to happen?

It should connect to Steam on start

### Instead of that, what actually happened?

It didn't connect to steam

I am using a Pterodactyl panel (Docker) and when I start the server, it initializes the depotdownloader to begin before anything else so that it can grab any updates from the game. Unfortunately, it only connects to Steam about 10% of the time. The rest of the time it doesn't connect to steam and after about 5 attempts it will boot the server up without validating or updating.

### Which operating system are you running on?

Linux

### Version

Latest (Auto updates)

### Command

./DepotDownloader -dir /home/container -app 258550 -os linux -validate

**Comment by xPaw** [comment] 2024-10-15 17:43
Duplicate of #546

**Closed by xPaw** 2024-10-15 17:43 UTC
Labels: bug
