### ISSUE TITLE
Connection to Steam failed inconsistently

### ISSUE THREAD

**Issue by Aragas** [SteamRE/DepotDownloader#543] opened 2024-09-25 13:18 UTC
### What did you expect to happen?

Expected to login to Steam successfully and download depot files
[Example](https://github.com/BUTR/Bannerlord.ButterLib/actions/runs/11030931899).
In this case the first connection succeeded, but not the second one

### Instead of that, what actually happened?

It timeout's a lot, but it still is able to connect to Steam sometimes when the pipeline is restarted

### Which operating system are you running on?

Windows

### Version

2.7.1

### Command

-app 261550 -depot 261551 261552 -beta v1.2.6 -username *** -os windows -osarch 64 -filelist ./.github/resources/FileFilters.regexp -dir bannerlord-beta

### Relevant log output

```shell
Using filelist: './.github/resources/FileFilters.regexp'.
Connecting to Steam3...Connection to Steam failed. Trying again
Connection to Steam failed. Trying again
Connection to Steam failed. Trying again
Connection to Steam failed. Trying again
Timeout connecting to Steam3.
Unable to get steam3 credentials.
Error: InitializeSteam failed
Error: Process completed with exit code 1.
```

### Additional Information

This seems to be a somewhat recent issue (less than 3 weeks).  
I was using previously 2.5.0 version and the timeout started to appear. I've tried to upgrade to 2.7.1, but it didn't resolve the issue.  
I'm not sure what is happening here - I was using GitHub Actions's Windows worker to connect for a few years and such gimmicks didn't appear before.  
I haven't used another account to test if this could be somehow account based.

**Comment by xPaw** [comment] 2024-09-25 18:18
Duplicate of #540

**Closed by xPaw** 2024-09-25 18:18 UTC
Labels: bug
